"use client";
import {useEffect,useMemo,useState} from "react";
import "./home.css";
type Branch={id:string;name:string;slug:string;address:string};
type Product={id:string;name:string;slug:string;description:string|null;price:string;image_url:string|null};
type Mode="DELIVERY"|"PICKUP";
const money=(v:string)=>"Gs. "+Number(v).toLocaleString("es-PY");

export default function Home(){
 const [branches,setBranches]=useState<Branch[]>([]),[branchId,setBranchId]=useState(""),[mode,setMode]=useState<Mode>("DELIVERY");
 const [products,setProducts]=useState<Product[]>([]),[locationOpen,setLocationOpen]=useState(false),[cart,setCart]=useState(0),[banner,setBanner]=useState(0);
 const selected=useMemo(()=>branches.find(x=>x.id===branchId),[branches,branchId]);
 useEffect(()=>{fetch("/api/branches").then(r=>r.json()).then((d:Branch[])=>{setBranches(d);const saved=localStorage.getItem("che_branch_id");setBranchId(saved&&d.some(x=>x.id===saved)?saved:(d[0]?.id||""));});},[]);
 useEffect(()=>{if(branchId){localStorage.setItem("che_branch_id",branchId);localStorage.setItem("che_order_type",mode);fetch("/api/menu?branch_id="+branchId).then(r=>r.json()).then(setProducts);}},[branchId,mode]);
 useEffect(()=>{const id=setInterval(()=>setBanner(n=>(n+1)%2),5000);return()=>clearInterval(id);},[]);
 return <main className="store">
  <div className="promo">PEDÍ DIRECTO · DELIVERY Y RETIRO</div>
  <header className="shopHeader"><a className="logo" href="/" aria-label="Che Bagels"><img src="/images/che-bagels-logo.png" alt="Che Bagels"/></a><nav><button onClick={()=>setLocationOpen(true)}>⌖ <span>{selected?.name||"Elegí sucursal"}</span></button><div className="fulfillment"><button className={mode==="DELIVERY"?"on":""} onClick={()=>setMode("DELIVERY")}>Delivery</button><button className={mode==="PICKUP"?"on":""} onClick={()=>setMode("PICKUP")}>Retiro</button></div></nav><button className="cartBtn">Mi pedido <b>{cart}</b></button></header>
  <section className="bannerCarousel" aria-label="Promociones"><div className="bannerTrack" style={{transform:`translateX(-${banner*100}%)`}}><a className="bannerSlide" href="#menu"><picture><source media="(max-width: 760px)" srcSet="/images/banners/che-hero-mobile.png"/><img src="/images/banners/che-hero-desktop.png" alt="Che Bagels - Pedí directo"/></picture></a><a className="bannerSlide" href="#menu"><picture><source media="(max-width: 760px)" srcSet="/images/banners/che-happy-hour-mobile.png"/><img src="/images/banners/che-happy-hour-desktop.png" alt="Che Bagels Happy Hour 2x1"/></picture></a></div><button className="bannerArrow prev" onClick={()=>setBanner(n=>(n+1)%2)} aria-label="Banner anterior">‹</button><button className="bannerArrow next" onClick={()=>setBanner(n=>(n+1)%2)} aria-label="Banner siguiente">›</button><div className="bannerDots">{[0,1].map(n=><button key={n} className={banner===n?"active":""} onClick={()=>setBanner(n)} aria-label={`Ver banner ${n+1}`}></button>)}</div></section>
  <section className="quickCats"><a href="#menu"><b>🥯</b><span>Bagels</span></a><a href="#menu"><b>🔥</b><span>Más pedidos</span></a><a href="#menu"><b>🍟</b><span>Combos</span></a><a href="#bakery"><b>🥐</b><span>Bakery</span></a><a href="#cafe"><b>☕</b><span>Café</span></a><a href="#menu"><b>🥤</b><span>Bebidas</span></a></section>
  <section className="catalog" id="menu"><div className="sectionTitle"><div><span>PARA MORDER, DISFRUTAR Y REPETIR</span><h2>Los más pedidos</h2></div><a href="/menu">Ver todo el menú →</a></div>
   <div className="cards">{products.slice(0,6).map((x,i)=>{const demoImage=x.slug==="bagel-demo-clasico"?"/images/products/bagel-clasico.png":x.slug==="bagel-demo-premium"?"/images/products/bagel-premium.png":null;return <article className="foodCard" key={x.id}><div className={"foodPic pic"+i}>{x.image_url||demoImage?<img src={x.image_url||demoImage||""} alt={x.name}/>:<><span>CHE.</span><small>Bagel artesanal</small></>}</div><div className="foodInfo"><h3>{x.name}</h3><p>{x.description||"Bagel artesanal preparado al momento con ingredientes frescos."}</p><div><strong>{money(x.price)}</strong><button onClick={()=>setCart(n=>n+1)} aria-label={"Agregar "+x.name}>+</button></div></div></article>})}</div>
   {!products.length&&<div className="emptyMenu">Estamos preparando el menú de esta sucursal…</div>}
  </section>
  <section className="brandBands"><article id="bakery"><span>CHE BAKERY</span><h2>Algo rico<br/>siempre suma.</h2><p>Panadería y opciones para acompañar cualquier momento.</p><button>VER BAKERY</button></article><article id="cafe"><span>MET CAFÉ</span><h2>Tu café,<br/>a tu manera.</h2><p>Café y bebidas para completar tu pedido.</p><button>VER CAFÉ</button></article></section>
  <section className="direct"><span>MENOS VUELTAS. MÁS CHE.</span><h2>Pedí directo.</h2><p>Elegí Delivery o Retiro, armá tu pedido y seguí su estado desde acá.</p><button onClick={()=>setLocationOpen(true)}>EMPEZAR PEDIDO →</button></section>
  <footer className="shopFooter"><div className="logo footerLogo"><img src="/images/che-bagels-logo.png" alt="Che Bagels"/></div><p>Che Bagels · Che Bakery · MET Café</p><small>Hecho para disfrutar.</small></footer>
  {cart>0&&<button className="floatingCart">Ver mi pedido <span>{cart} {cart===1?"producto":"productos"}</span> →</button>}
  {locationOpen&&<div className="modalBack" onClick={()=>setLocationOpen(false)}><section className="locationModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLocationOpen(false)}>×</button><span className="modalKicker">TU PEDIDO</span><h2>¿Dónde estás?</h2><p>Elegí la sucursal y cómo querés recibir tu pedido.</p><div className="modalModes"><button className={mode==="DELIVERY"?"active":""} onClick={()=>setMode("DELIVERY")}>Delivery</button><button className={mode==="PICKUP"?"active":""} onClick={()=>setMode("PICKUP")}>Retiro</button></div><div className="modalBranches">{branches.map(b=><button className={b.id===branchId?"active":""} key={b.id} onClick={()=>setBranchId(b.id)}><span><b>{b.name}</b><small>{b.address}</small></span><i>{b.id===branchId?"✓":""}</i></button>)}</div><button className="modalDone" onClick={()=>setLocationOpen(false)}>LISTO, VER MENÚ</button></section></div>}
 </main>
}