"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {CartProduct,CartSelection,useCart} from "../../cart-context";
type Product=CartProduct&{description:string|null;category_name?:string|null;category_slug?:string|null};
const money=(v:number|string)=>"Gs. "+Number(v).toLocaleString("es-PY");
const images:Record<string,string>={"american-burger":"/images/products/bagel-burger.png","crunchi-de-pollo":"/images/products/bagel-crunch-pollo.png","desmechado-clasico":"/images/products/bagel-desmechado.png","bec-bacon-egg-cheese":"/images/products/bagel-huevo-panceta.png"};
export default function ProductPage(){
 const params=useParams<{slug:string}>(),slug=decodeURIComponent(params.slug);
 const [items,setItems]=useState<Product[]>([]),[loading,setLoading]=useState(true),[qty,setQty]=useState(1),[notes,setNotes]=useState(""),[side,setSide]=useState(""),[drink,setDrink]=useState("");
 const {add,count,total,openCart}=useCart();
 useEffect(()=>{(async()=>{try{const branches=await fetch("/api/branches").then(r=>r.json());const saved=localStorage.getItem("che_branch_id");const branch=saved&&branches.some((x:{id:string})=>x.id===saved)?saved:(branches[0]?.id||"");if(branch){localStorage.setItem("che_branch_id",branch);setItems(await fetch("/api/menu?branch_id="+branch).then(r=>r.json()))}}finally{setLoading(false)}})()},[]);
 const product=items.find(x=>x.slug===slug),sides=useMemo(()=>items.filter(x=>x.category_slug==="papas-fritas"),[items]),drinks=useMemo(()=>items.filter(x=>x.category_slug==="bebidas"),[items]);
 const selections=useMemo(()=>{const out:CartSelection[]=[];const s=sides.find(x=>x.id===side),d=drinks.find(x=>x.id===drink);if(s)out.push({key:"side:"+s.id,productId:s.id,label:s.name,price:Number(s.price)});if(d)out.push({key:"drink:"+d.id,productId:d.id,label:d.name,price:Number(d.price)});return out},[side,drink,sides,drinks]);
 const unit=product?Number(product.price)+selections.reduce((n,x)=>n+x.price,0):0;
 if(loading)return <main className="productPage"><div className="productLoading">Cargando producto…</div></main>;
 if(!product)return <main className="productPage"><div className="productMissing"><h1>Producto no disponible</h1><p>Este producto no está disponible en la sucursal seleccionada.</p><a href="/menu">← Volver al menú</a></div></main>;
 const src=product.image_url||images[product.slug];
 return <main className={count>0?"store productPage hasCart":"store productPage"}><div className="promo">PEDÍ DIRECTO · DELIVERY Y RETIRO</div><header className="shopHeader"><a className="logo" href="/"><img src="/images/che-bagels-logo.png" alt="Che Bagels"/></a><nav><a className="menuBack" href="/menu">← Menú</a></nav><button className="cartBtn" onClick={openCart}>Mi pedido <b>{count}</b></button></header>
 <section className="productDetail"><div className="productVisual">{src?<img src={src} alt={product.name}/>:<div className="productPlaceholder"><b>CHE.</b><span>{product.category_name}</span></div>}</div><div className="productConfig"><a className="productBreadcrumb" href="/menu">MENÚ / {product.category_name||"PRODUCTO"}</a><h1>{product.name}</h1>{product.description&&<p className="productDescription">{product.description}</p>}<strong className="productPrice">{money(product.price)}</strong>
 {(sides.length>0||drinks.length>0)&&<section className="completeOrder"><div className="configHeading"><span>COMPLETÁ TU PEDIDO</span><h2>¿Querés sumarle algo?</h2><p>Elegí papas y bebida. Se suman al precio normal del menú.</p></div>
 {sides.length>0&&<fieldset><legend>Papas <small>Opcional</small></legend><label className={!side?"optionRow selected":"optionRow"}><input type="radio" name="side" checked={!side} onChange={()=>setSide("")}/><span>Sin papas</span><b>Gs. 0</b></label>{sides.map(x=><label className={side===x.id?"optionRow selected":"optionRow"} key={x.id}><input type="radio" name="side" checked={side===x.id} onChange={()=>setSide(x.id)}/><span>{x.name}</span><b>+ {money(x.price)}</b></label>)}</fieldset>}
 {drinks.length>0&&<fieldset><legend>Bebida <small>Opcional</small></legend><label className={!drink?"optionRow selected":"optionRow"}><input type="radio" name="drink" checked={!drink} onChange={()=>setDrink("")}/><span>Sin bebida</span><b>Gs. 0</b></label>{drinks.map(x=><label className={drink===x.id?"optionRow selected":"optionRow"} key={x.id}><input type="radio" name="drink" checked={drink===x.id} onChange={()=>setDrink(x.id)}/><span>{x.name}</span><b>+ {money(x.price)}</b></label>)}</fieldset>}</section>}
 <label className="productNotes">¿Alguna indicación? <small>Opcional</small><textarea maxLength={500} rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ej: sin cebolla, cortar a la mitad…"/></label><div className="productBuy"><div className="productQty"><button onClick={()=>setQty(q=>Math.max(1,q-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(q=>Math.min(50,q+1))}>+</button></div><button className="productAdd" onClick={()=>{add(product,selections,notes,qty);openCart()}}>AGREGAR · {money(unit*qty)}</button></div></div></section>
 <footer className="shopFooter"><div className="logo footerLogo"><img src="/images/che-bagels-logo.png" alt="Che Bagels"/></div><p>Che Bagels · Che Bakery · MET Café</p><small>Delivery · Retiro · Pedí directo</small></footer>{count>0&&<button className="floatingCart" onClick={openCart}><b>Ver mi pedido</b><span>{count} {count===1?"producto":"productos"} · {money(total)} →</span></button>}</main>
}