"use client";
import {pointsLabel} from "../club-points";
import {useEffect,useMemo,useRef,useState} from "react";
import {useCart} from "../cart-context";
type Product={id:string;name:string;slug:string;description:string|null;price:string;image_url:string|null;category_name?:string|null;category_slug?:string|null};
type Branch={id:string;name:string};
const money=(v:string|number)=>"Gs. "+Number(v).toLocaleString("es-PY");
const ORDER=["bagels-calientes","bagels-frios","tablas","boxes","papas-fritas","ensaladas","bebidas"];
const images:Record<string,string>={"american-burger":"/images/products/bagel-burger.png","crunchi-de-pollo":"/images/products/bagel-crunch-pollo.png","desmechado-clasico":"/images/products/bagel-desmechado.png","bec-bacon-egg-cheese":"/images/products/bagel-huevo-panceta.png"};
const assetFallback=(event:React.SyntheticEvent<HTMLImageElement>)=>{const img=event.currentTarget;if(img.dataset.fallback==="1"){img.style.display="none";return;}const original=img.dataset.originalPath||new URL(img.src).pathname;if(!original.startsWith("/images/")){img.style.display="none";return;}img.dataset.fallback="1";img.dataset.originalPath=original;const picture=img.closest("picture");picture?.querySelectorAll("source").forEach(source=>source.remove());img.src="https://raw.githubusercontent.com/equantum-py/chebagels/feat/che-club-review/apps/web/public"+original;};
export default function Menu(){
 const [items,setItems]=useState<Product[]>([]),[mode,setMode]=useState("DELIVERY"),[loading,setLoading]=useState(true),[activeCat,setActiveCat]=useState("");
 const {count:cart,total,add,openCart}=useCart();
 const catBarRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{setMode(localStorage.getItem("che_order_type")||"DELIVERY");(async()=>{try{const branches:Branch[]=await fetch("/api/branches").then(r=>r.json());const saved=localStorage.getItem("che_branch_id");const branch=saved&&branches.some(x=>x.id===saved)?saved:(branches[0]?.id||"");if(branch){localStorage.setItem("che_branch_id",branch);const data=await fetch("/api/menu?branch_id="+branch).then(r=>r.json());setItems(data)}}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!items.length)return;const id=decodeURIComponent(location.hash.slice(1));if(!id)return;requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"}))},[items]);
 useEffect(()=>{if(!items.length)return;const ids=ORDER.filter(id=>document.getElementById(id));const update=()=>{const y=window.scrollY+155;let current=ids[0]||"";for(const id of ids){const el=document.getElementById(id);if(el&&el.offsetTop<=y)current=id}if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-40)current=ids[ids.length-1]||current;setActiveCat(current)};update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update)},[items]);
 useEffect(()=>{const active=catBarRef.current?.querySelector<HTMLAnchorElement>(`a[href="#${activeCat}"]`);active?.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})},[activeCat]);
 const cats=useMemo(()=>ORDER.map(slug=>({slug,name:items.find(x=>x.category_slug===slug)?.category_name||slug})).filter(c=>items.some(x=>x.category_slug===c.slug)),[items]);
 return <main className={cart>0?"store menuPage hasCart":"store menuPage"}><div className="promo">PEDÍ DIRECTO · DELIVERY Y RETIRO</div>
 <section className="menuIntro"><span>MENÚ CHE BAGELS</span><h1>Elegí tu favorito.</h1><p>Todo el menú organizado por categoría.</p></section>
 <nav ref={catBarRef} className="quickCats menuCats">{cats.map(c=><a className={activeCat===c.slug?"active":""} href={"#"+c.slug} key={c.slug}>{c.name}</a>)}</nav>
 <section className="catalog fullCatalog">{cats.map(c=><section className="menuCategory" id={c.slug} key={c.slug}><div className="categoryHeading"><span>MENÚ CHE BAGELS</span><h2>{c.name}</h2></div><div className="cards">{items.filter(x=>x.category_slug===c.slug).map((x,i)=>{const src=x.image_url||images[x.slug];return <article className="foodCard" key={x.id}><a className={"foodPic pic"+i} href={"/producto/"+x.slug}>{src?<img loading="lazy" onError={assetFallback} src={src} alt={x.name}/>:<div className="cheProductPlaceholder" role="img" aria-label={"Imagen de "+x.name+" próximamente disponible"}><span className="chePlaceholderLogo">CHE.</span><span className="chePlaceholderName">{x.name}</span><small>{c.name}</small></div>}</a><div className="foodInfo"><h3><a className="productLink" href={"/producto/"+x.slug}>{x.name}</a></h3>{x.description&&<p>{x.description}</p>}<p className="clubPointsEstimate">{pointsLabel(Number(x.price))} <small>· Demo</small></p><div className="foodAction"><strong>{money(x.price)}</strong><button onClick={()=>add(x)} aria-label={"Agregar "+x.name}>Agregar</button></div></div></article>})}</div></section>)}{loading&&<div className="emptyMenu">Cargando menú…</div>}{!loading&&!items.length&&<div className="emptyMenu">No pudimos cargar el menú. Volvé a intentar.</div>}</section>
 {cart>0&&<button className="floatingCart" onClick={openCart}><b>Ver mi pedido</b><span>{cart} {cart===1?"producto":"productos"} · {money(total)} →</span></button>}</main>
}