"use client";
import {useState} from "react";
import Link from "next/link";
const rewards=[{id:"cafe",name:"Café de cortesía",cost:150,detail:"Beneficio de ejemplo para MET Café"},{id:"papas",name:"Papas rústicas",cost:250,detail:"Beneficio de ejemplo para CHE Bagels"},{id:"bagel",name:"Beneficio especial Bagel",cost:500,detail:"Recompensa de ejemplo, sujeta a aprobación"}];
export default function ClubDemo(){
 const [balance,setBalance]=useState(225);
 const [history,setHistory]=useState([{id:1,label:"Saldo inicial de ejemplo",date:"Datos ficticios",points:225}]);
 const [notice,setNotice]=useState("");
 const [tab,setTab]=useState<"resumen"|"premios"|"historial">("resumen");
 const redeem=(id:string)=>{const reward=rewards.find(r=>r.id===id);if(!reward)return;if(balance<reward.cost){setNotice("Todavía te faltan "+(reward.cost-balance)+" puntos para este beneficio.");return;}setBalance(b=>b-reward.cost);setHistory(h=>[{id:Date.now(),label:"Canje demo: "+reward.name,date:"Simulación",points:-reward.cost},...h]);setNotice("¡Canje simulado! En la versión real recibirías un comprobante.");};
 const purchase=()=>{setBalance(b=>b+45);setHistory(h=>[{id:Date.now(),label:"Pedido demo de Gs. 45.000",date:"Simulación",points:45},...h]);setNotice("Se acreditaron 45 puntos de demostración.");};
 const faqs=[{q:"¿Cómo puedo ganar puntos?",a:"En esta demostración, una compra completada genera puntos estimados según el importe de los productos. La regla definitiva todavía debe aprobarse."},{q:"¿Cuánto valen los puntos?",a:"El ejemplo usa 1 punto por cada Gs. 1.000 de productos y adicionales. No es una regla comercial vigente."},{q:"¿Cuándo se acreditan mis puntos?",a:"En la versión real, solo después de validar la identidad del cliente y completar el pedido. La acreditación real aún no está habilitada."},{q:"¿Puedo canjear mis puntos?",a:"En esta página podés simular canjes. Todavía no se entregan productos ni cupones reales."},{q:"¿Los puntos se guardan al recargar?",a:"No. Esta demo funciona únicamente en memoria y vuelve a su saldo inicial al recargar."},{q:"¿Puedo usar puntos con delivery o retiro?",a:"La modalidad no cambia esta demostración. Las reglas de elegibilidad reales se definirán antes del lanzamiento."}];
 const reset=()=>{setBalance(225);setHistory([{id:1,label:"Saldo inicial de ejemplo",date:"Datos ficticios",points:225}]);setNotice("Demo reiniciada.");setTab("resumen")};
 return <main className="clubPremium">
 <style>{`
 .clubPremium{--wine:#8f2428;--ink:#281715;--cream:#fff7e9;--muted:#75645d;min-height:100vh;background:#fff;color:var(--ink);font-family:Arial,Helvetica,sans-serif}
 .clubPremium *{box-sizing:border-box}.clubPremium button{cursor:pointer;font:inherit}.clubPremium a{text-decoration:none;color:inherit}
 .cpTop{position:sticky;top:0;z-index:100;max-width:none;margin:auto;padding:17px max(24px,calc((100vw - 1200px)/2));display:flex;align-items:center;justify-content:space-between;gap:25px;background:#fff;border-bottom:1px solid #eee1d5;min-height:75px}
 .cpLogo{white-space:nowrap;font-size:24px;font-weight:900;color:var(--wine);letter-spacing:-1px}.cpTop a:last-child{font-size:13px;font-weight:800}
 .cpNav{display:flex;gap:22px;align-items:center}.cpNav a{font-size:13px;font-weight:800;white-space:nowrap}.cpNav a[aria-current=page]{color:#8f2428}.cpNavActions{display:flex;align-items:center;gap:12px}.cpBack{font-size:13px;font-weight:800;white-space:nowrap;color:#8f2428!important}.cpNavMobile{display:none;position:relative}.cpNavMobile summary{list-style:none;cursor:pointer;font-size:23px}.cpNavMobile summary::-webkit-details-marker{display:none}.cpNavMobile>div{position:absolute;right:0;top:40px;min-width:205px;background:white;border:1px solid #e8d8c9;box-shadow:0 12px 30px #2b171422;border-radius:10px;padding:8px}.cpNavMobile a{display:block;padding:12px;font-size:14px;font-weight:800} @media(max-width:950px){.cpNav{display:none}.cpNavMobile{display:block}.cpTop{padding:14px 20px}} @media(max-width:560px){.cpTop{min-height:65px}.cpLogo{font-size:21px}.cpBack{font-size:12px}} .cpHero{background:var(--cream);overflow:hidden}.cpHeroInner{max-width:1200px;margin:auto;display:grid;grid-template-columns:1fr 1fr;align-items:center;min-height:440px;gap:32px;padding:44px 28px}
 .cpEyebrow{font-size:12px;font-weight:900;color:var(--wine);letter-spacing:1.7px}.cpHero h1{font-size:clamp(44px,5.6vw,76px);line-height:.99;letter-spacing:-.055em;margin:18px 0}.cpHero p{font-size:17px;line-height:1.6;max-width:500px;color:#64514b}
 .cpHeroArt{height:330px;display:grid;place-items:center;position:relative;background:#f2e3d0;border-radius:22px;overflow:hidden}
 .cpHeroArt:before{content:"";width:270px;height:270px;border-radius:50%;background:#8f2428;position:absolute;right:12%;top:9%}
 .cpHeroArt img{position:relative;z-index:1;width:88%;height:92%;object-fit:contain;filter:drop-shadow(0 22px 22px #28171530)}
 .cpDemo{display:inline-block;background:#fff;border:1px solid #e6c9b8;border-radius:99px;padding:8px 12px;color:var(--wine);font-size:11px;font-weight:900}
 .cpMain{max-width:1200px;margin:auto;padding:40px 28px 80px}.cpDashboard{display:grid;grid-template-columns:1.2fr .8fr;gap:20px}
 .cpBalance{background:var(--wine);color:white;padding:30px 34px;border-radius:18px}.cpBalance>span,.cpNext>span{font-size:11px;font-weight:900;letter-spacing:1.3px}
 .cpBalance h2{font-size:clamp(52px,6vw,76px);line-height:1;margin:14px 0 10px;letter-spacing:-3px}.cpBalance h2 small{font-size:18px;letter-spacing:0}
 .cpBalance p{font-size:13px;color:#f2dcd6}.cpActions{display:flex;flex-wrap:wrap;gap:9px;margin-top:22px}
 .cpBtn{border:0;background:var(--wine);color:#fff;padding:13px 18px;border-radius:7px;font-weight:800;font-size:13px}
 .cpBalance .cpBtn{background:white;color:var(--wine)}.cpBalance .cpBtn.secondary{background:#ffffff20;color:white;border:1px solid #ffffff60}
 .cpNext{background:#fff8ef;border:1px solid #eddfd0;border-radius:18px;padding:30px}.cpNext h3{font-size:25px;margin:17px 0 7px}
 .cpNext p{font-size:13px;color:var(--muted)}.cpTrack{height:10px;border-radius:20px;background:#e7d8c8;margin:20px 0 8px;overflow:hidden}.cpTrack i{display:block;height:100%;background:var(--wine);border-radius:20px}
 .cpHeading{margin:64px 0 22px}.cpHeading h2{font-size:clamp(30px,3.8vw,44px);letter-spacing:-1.6px;margin:0 0 10px}.cpHeading p{color:var(--muted);font-size:15px;line-height:1.5;margin:0}
 .cpSteps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.cpStep{padding:25px;border:1px solid #ecded1;border-radius:15px;background:#fff}
 .cpStep b{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:#f8e6d8;color:var(--wine);font-size:19px}.cpStep h3{font-size:21px;margin:22px 0 9px}.cpStep p{font-size:14px;line-height:1.6;color:var(--muted)}
 .cpRewards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.cpReward{border:1px solid #eddfd0;border-radius:16px;overflow:hidden;display:flex;flex-direction:column;background:#fff}
 .cpRewardImg{height:210px;background:#f6eadb;display:grid;place-items:center;overflow:hidden}.cpRewardImg img{width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 15px 15px #29171123)}
 .cpRewardBody{padding:22px;display:flex;flex:1;flex-direction:column}.cpRewardBody h3{font-size:22px;margin:0 0 8px}.cpRewardBody p{font-size:13px;color:var(--muted);line-height:1.5;margin:0 0 18px}.cpRewardBody strong{color:var(--wine);font-size:23px;margin-top:auto;margin-bottom:17px}
 .cpRewardBody button{width:100%}.cpFaq{max-width:850px}.cpFaq details{border-bottom:1px solid #e8ddd2;padding:18px 0}.cpFaq summary{font-weight:800;font-size:17px;cursor:pointer;list-style:none;display:flex;justify-content:space-between;gap:20px}.cpFaq summary:after{content:"+";font-size:22px;color:var(--wine)}.cpFaq details[open] summary:after{content:"−"}.cpFaq details p{font-size:14px;line-height:1.7;color:var(--muted);max-width:740px}
 .cpTabs{display:flex;gap:9px;flex-wrap:wrap;margin:34px 0 18px}.cpTabs button{padding:11px 17px;border:1px solid #e3d2c3;background:white;border-radius:40px;font-weight:800;font-size:13px}.cpTabs button[aria-selected=true]{background:var(--wine);color:white;border-color:var(--wine)}
 .cpHistory{border:1px solid #e8dace;border-radius:14px;padding:10px 25px}.cpHistoryRow{display:flex;justify-content:space-between;gap:15px;padding:16px 0;border-bottom:1px solid #eee2d8}.cpHistoryRow:last-child{border:0}.cpHistoryRow small{display:block;color:var(--muted);margin-top:5px}
 .cpNotice{padding:15px 20px;background:#f5e7d9;color:var(--wine);border-radius:10px;margin-top:20px;font-weight:700}.cpDisclaimer{font-size:12px;line-height:1.6;color:var(--muted);margin-top:45px}
 @media(max-width:800px){.cpHeroInner,.cpDashboard{grid-template-columns:1fr}.cpHeroInner{padding:38px 20px}.cpHeroArt{height:270px}.cpMain{padding:28px 20px 60px}.cpSteps,.cpRewards{grid-template-columns:repeat(2,minmax(0,1fr))}}
 @media(max-width:560px){.cpTop{padding:16px}.cpHeroInner{gap:18px}.cpHero h1{font-size:44px}.cpHeroArt{height:215px}.cpBalance,.cpNext{padding:23px}.cpSteps,.cpRewards{grid-template-columns:1fr}.cpRewardImg{height:200px}.cpHeading{margin-top:45px}.cpBalance h2{font-size:62px}.cpActions .cpBtn{width:100%}}
 `}</style>
 
 <section className="cpHero"><div className="cpHeroInner"><div><span className="cpDemo">DEMO INTERACTIVA · PUNTOS FICTICIOS</span><div className="cpEyebrow" style={{marginTop:24}}>CHE CLUB · BENEFICIOS</div><h1>Tus favoritos ahora tienen premio.</h1><p>Pedí lo que más te gusta, sumá puntos y descubrí beneficios pensados para vos.</p><a className="cpBtn" href="#recompensas" style={{display:"inline-block",marginTop:15}}>Explorar recompensas →</a></div><div className="cpHeroArt"><img src="/images/products/bagel-burger.png" alt="Bagel artesanal CHE Bagels" onError={e=>{e.currentTarget.src="https://raw.githubusercontent.com/equantum-py/chebagels/feat/che-club-review/apps/web/public/images/products/bagel-burger.png"}}/></div></div></section>
 <div className="cpMain"><section className="cpDashboard"><article className="cpBalance"><span>MI CHE CLUB · SALDO DE EJEMPLO</span><h2>{balance.toLocaleString("es-PY")} <small>puntos</small></h2><p>Tu saldo de demostración. No son puntos reales.</p><div className="cpActions"><button className="cpBtn" onClick={purchase}>Simular compra · +45 puntos</button><button className="cpBtn secondary" onClick={reset}>Reiniciar demo</button></div></article><article className="cpNext"><span>ESTÁS CERCA DE TU PRÓXIMO PREMIO</span><h3>Papas rústicas</h3><p>Meta de ejemplo · 250 puntos</p><div className="cpTrack"><i style={{width:Math.min(100,balance/250*100)+"%"}}/></div><p>{balance>=250?"¡Ya alcanzaste este beneficio!":"Te faltan "+(250-balance)+" puntos para llegar"}</p></article></section>
 <section className="cpHeading"><h2>Así de fácil es ganar</h2><p>Un recorrido simple para que cada compra cuente.</p></section><div className="cpSteps"><article className="cpStep"><b>01</b><h3>Pedí directo</h3><p>Elegí tus favoritos y comprá desde nuestro ecommerce.</p></article><article className="cpStep"><b>02</b><h3>Sumá puntos</h3><p>Visualizá puntos estimados en productos y carrito.</p></article><article className="cpStep"><b>03</b><h3>Elegí tu premio</h3><p>Explorá las recompensas que podrías canjear.</p></article></div>
 <section id="recompensas" className="cpHeading"><h2>Más puntos, más cosas ricas.</h2><p>Recompensas ilustrativas de CHE Club. Los valores y productos están sujetos a aprobación.</p></section><div className="cpRewards">{rewards.map(r=><article className="cpReward" key={r.id}><div className="cpRewardImg"><img src={r.id==="cafe"?"/images/products/bagel-huevo-panceta.png":r.id==="papas"?"/images/products/bagel-crunch-pollo.png":"/images/products/bagel-burger.png"} alt={"Imagen ilustrativa de "+r.name} onError={e=>{const img=e.currentTarget;if(img.dataset.fallback)return;img.dataset.fallback="1";img.src="https://raw.githubusercontent.com/equantum-py/chebagels/feat/che-club-review/apps/web/public"+new URL(img.src).pathname}}/></div><div className="cpRewardBody"><h3>{r.name}</h3><p>{r.detail}</p><strong>{r.cost} puntos</strong><button className="cpBtn" onClick={()=>redeem(r.id)}>{balance>=r.cost?"Simular canje":"Ver cuánto me falta"}</button></div></article>)}</div>
 <nav className="cpTabs" aria-label="CHE Club"><button aria-selected={tab==="resumen"} onClick={()=>setTab("resumen")}>Mi resumen</button><button aria-selected={tab==="historial"} onClick={()=>setTab("historial")}>Mis movimientos</button></nav>
 {tab==="historial"&&<section className="cpHistory"><h3>Mis movimientos de ejemplo</h3>{history.map(h=><div className="cpHistoryRow" key={h.id}><div><b>{h.label}</b><small>{h.date}</small></div><strong>{h.points>0?"+":""}{h.points} pts</strong></div>)}</section>}
 {tab==="resumen"&&<p style={{fontSize:14,color:"#75645d"}}>Simulá una compra o un canje para ver cómo cambia tu saldo. Abrí “Mis movimientos” para revisar el historial.</p>}
 <section className="cpHeading"><h2>Preguntas frecuentes</h2><p>Todo lo que necesitás saber sobre esta demostración.</p></section><section className="cpFaq">{faqs.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</section>
 {notice&&<p className="cpNotice" role="status">{notice}</p>}<p className="cpDisclaimer"><b>CHE Club en demostración.</b> Las recompensas, puntos y canjes son ficticios. No hay acreditaciones reales ni se modifican pedidos. El saldo se reinicia al recargar.</p></div></main>
}
