"use client";
import {useState} from "react";
import Link from "next/link";
const rewards=[{id:"cafe",name:"Café de cortesía",cost:150,detail:"Beneficio de ejemplo para MET Café"},{id:"papas",name:"Papas rústicas",cost:250,detail:"Beneficio de ejemplo para CHE Bagels"},{id:"bagel",name:"Beneficio especial Bagel",cost:500,detail:"Recompensa de ejemplo, sujeta a aprobación"}];
export default function ClubDemo(){
 const [balance,setBalance]=useState(225);
 const [history,setHistory]=useState([{id:1,label:"Saldo inicial de ejemplo",date:"Datos ficticios",points:225}]);
 const [notice,setNotice]=useState("");
 const [tab,setTab]=useState<"resumen"|"premios"|"historial">("resumen");
 const redeem=(id:string)=>{const reward=rewards.find(r=>r.id===id);if(!reward)return;if(balance<reward.cost){setNotice("Todavía te faltan "+(reward.cost-balance)+" puntos para este beneficio.");return;}setBalance(b=>b-reward.cost);setHistory(h=>[{id:Date.now(),label:"Canje demo: "+reward.name,date:"Simulación",points:-reward.cost},...h]);setNotice("¡Canje simulado! En la versión real recibirías un comprobante.");};
 const purchase=()=>{setBalance(b=>b+45);setHistory(h=>[{id:Date.now(),label:"Pedido demo de Gs. 45.000",date:"Simulación",points:45},...h]);setNotice("Se acreditaron 45 puntos de demostración.");};
 const faqs=[{q:"¿Cómo puedo ganar puntos?",a:"En esta demostración, una compra completada genera puntos estimados según el importe de los productos. La regla definitiva todavía debe aprobarse."},{q:"¿Cuánto valen los puntos?",a:"El ejemplo usa 1 punto por cada Gs. 1.000 de productos y adicionales. No es una regla comercial vigente."},{q:"¿Cuándo se acreditan mis puntos?",a:"En la versión real, solo después de validar la identidad del cliente y completar el pedido. La acreditación real aún no está habilitada."},{q:"¿Puedo canjear mis puntos?",a:"En esta página podés simular canjes. Todavía no se entregan productos ni cupones reales."},{q:"¿Los puntos se guardan al recargar?",a:"No. Esta demo funciona únicamente en memoria y vuelve a su saldo inicial al recargar."},{q:"¿Puedo usar puntos con delivery o retiro?",a:"La modalidad no cambia esta demostración. Las reglas de elegibilidad reales se definirán antes del lanzamiento."}];
 const reset=()=>{setBalance(225);setHistory([{id:1,label:"Compra web completada",date:"Ejemplo de pedido",points:225}]);setNotice("Demo reiniciada.");setTab("resumen")};
 return <main className="cd"><style>{`
 .cd{min-height:100vh;background:#fff;color:#301b19;font-family:Arial,Helvetica,sans-serif}.cd *{box-sizing:border-box}.cd a{text-decoration:none}.cdHeader{max-width:1080px;margin:auto;padding:20px 24px;display:flex;align-items:center;justify-content:space-between;gap:12px}.cdBrand{font-size:24px;font-weight:900;color:#8f2428}.cdBack{font-size:13px;font-weight:700;color:#8f2428}.cdHero{background:#fff8ec;color:#301b19;padding:54px 24px;border-bottom:1px solid #ebdfd0}.cdHeroInner{max-width:1032px;margin:auto}.cdEyebrow{font-size:12px;letter-spacing:1.5px;font-weight:800;color:#8f2428}.cdHero h1{font-size:clamp(34px,5vw,60px);letter-spacing:-1.5px;margin:15px 0 12px}.cdHero p{max-width:640px;line-height:1.55;color:#63504a}.cdDemoBadge{display:inline-block;border:1px solid #b77873;padding:7px 11px;border-radius:100px;font-size:12px;font-weight:800}.cdBody{max-width:1080px;margin:0 auto;padding:30px 24px 70px}.cdGrid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.cdCard{border:1px solid #e9d9c9;background:#fff;border-radius:10px;padding:25px}.cdLabel{font-size:12px;letter-spacing:1px;font-weight:800;color:#8f2428}.cdBalance{font-size:clamp(48px,7vw,72px);font-weight:900;letter-spacing:-3px;margin:10px 0}.cdMuted{color:#776760;font-size:14px;line-height:1.55}.cdProgress{height:10px;background:#f2e6d7;border-radius:20px;overflow:hidden;margin:18px 0 8px}.cdProgress span{display:block;height:100%;background:#8f2428;border-radius:20px}.cdButton{border:0;border-radius:7px;background:#8f2428;color:white;padding:13px 17px;font-weight:800;cursor:pointer}.cdButton:disabled{background:#d9c6be;color:#76655d;cursor:not-allowed}.cdButtonAlt{background:#f4e5d3;color:#8f2428}.cdActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.cdTabs{display:flex;gap:8px;flex-wrap:wrap;margin:30px 0 18px}.cdTabs button{padding:11px 18px;border:1px solid #ddcbb9;border-radius:30px;background:#fff;color:#442a26;cursor:pointer;font-weight:800}.cdTabs button[aria-selected=true]{background:#8f2428;color:#fff;border-color:#8f2428}.cdRewards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.cdReward h3{font-size:20px;margin:12px 0 8px}.cdReward .cdButton{width:100%;margin-top:18px}.cdReward strong{color:#8f2428}.cdRow{display:flex;justify-content:space-between;gap:12px;padding:17px 0;border-bottom:1px solid #efe4d7}.cdRow:last-child{border-bottom:0}.cdNotice{padding:14px 18px;background:#f4e5d3;border-radius:8px;margin-top:20px;font-size:14px}.cdFine{font-size:12px;color:#806e65;line-height:1.6;margin-top:26px}.cdMini{font-size:26px;margin-bottom:8px}@media(max-width:760px){.cdGrid,.cdRewards,.cdSteps{grid-template-columns:1fr}.cdHero{padding:42px 20px}.cdBody{padding:20px 16px 50px}.cdCard{padding:20px}.cdBalance{letter-spacing:-1px}}
 `}</style>
 <header className="cdHeader"><Link href="/club" className="cdBrand">CHE<span style={{fontWeight:400}}>.</span> CLUB</Link><Link href="/" className="cdBack">Volver al menú →</Link></header>
 <section className="cdHero"><div className="cdHeroInner"><span className="cdDemoBadge">DEMO INTERACTIVA · DATOS FICTICIOS</span><div className="cdEyebrow" style={{marginTop:22}}>BENEFICIOS POR COMPRAR DIRECTO</div><h1>Tu fidelidad tiene premio.</h1><p>Así podría funcionar CHE Club: acumulás puntos con tus pedidos, seguís tu progreso y canjeás beneficios de las marcas CHE.</p></div></section>
 <div className="cdBody"><section className="cdGrid"><article className="cdCard"><div className="cdLabel">MIS PUNTOS · CUENTA DE EJEMPLO</div><div className="cdBalance">{balance.toLocaleString("es-PY")} <span style={{fontSize:18,letterSpacing:0}}>pts</span></div><div className="cdMuted">Saldo disponible en esta simulación.</div><div className="cdActions"><button className="cdButton" onClick={purchase}>Simular compra de Gs. 45.000 (+45 pts)</button><button className="cdButton cdButtonAlt" onClick={reset}>Reiniciar demo</button></div></article><article className="cdCard"><div className="cdLabel">TU PRÓXIMO BENEFICIO</div><h2 style={{margin:"15px 0 4px"}}>Papas rústicas</h2><div className="cdMuted">Meta de ejemplo: 250 puntos</div><div className="cdProgress"><span style={{width:Math.min(100,balance/250*100)+"%"}}/></div><div className="cdMuted">{balance>=250?"¡Ya tenés los puntos necesarios!":"Te faltan "+(250-balance)+" puntos"}</div><p className="cdFine">Los beneficios, sus valores y las reglas de acumulación están sujetos a aprobación.</p></article></section>
 <nav className="cdTabs" aria-label="Secciones de CHE Club"><button aria-selected={tab==="resumen"} onClick={()=>setTab("resumen")}>Cómo funciona</button><button aria-selected={tab==="premios"} onClick={()=>setTab("premios")}>Recompensas</button><button aria-selected={tab==="historial"} onClick={()=>setTab("historial")}>Mis movimientos</button></nav>
 {tab==="resumen"&&<section className="cdRewards"><article className="cdCard"><div className="cdMini">🛍️</div><h3>1. Pedí directo</h3><p className="cdMuted">Comprá en la web y elegí Delivery o Retiro.</p></article><article className="cdCard"><div className="cdMini">⭐</div><h3>2. Sumá puntos</h3><p className="cdMuted">Ejemplo: 1 punto por cada Gs. 1.000 de compra completada.</p></article><article className="cdCard"><div className="cdMini">🎁</div><h3>3. Canjeá</h3><p className="cdMuted">Elegí recompensas disponibles cuando alcances los puntos necesarios.</p></article></section>}
 {tab==="premios"&&<section className="cdRewards">{rewards.map(r=><article className="cdCard cdReward" key={r.id}><div className="cdRewardVisual" aria-hidden="true">{r.id==="cafe"?"☕":r.id==="papas"?"🍟":"🥯"}</div><h3>{r.name}</h3><p className="cdMuted">{r.detail}</p><strong>{r.cost} puntos</strong><button className="cdButton" onClick={()=>redeem(r.id)}>{balance>=r.cost?"Simular canje":"Ver cuánto me falta"}</button></article>)}</section>}
 {tab==="historial"&&<section className="cdCard"><h2>Mis movimientos</h2>{history.map(h=><div className="cdRow" key={h.id}><div><b>{h.label}</b><div className="cdMuted">{h.date}</div></div><strong style={{color:h.points>=0?"#28764c":"#8f2428"}}>{h.points>0?"+":""}{h.points} pts</strong></div>)}</section>}
 <section className="cdEditorial"><h2>Cómo ganar puntos y canjear tus favoritos</h2><p>Conocé el recorrido pensado para CHE Club. Los beneficios y valores que ves son ilustrativos hasta la aprobación comercial.</p><div className="cdSteps"><article className="cdStep"><span className="cdStepNumber">1</span><h3>Elegí tus favoritos</h3><p>Pedí desde CHE Bagels y seleccioná delivery o retiro.</p></article><article className="cdStep"><span className="cdStepNumber">2</span><h3>Sumá puntos</h3><p>Visualizá los puntos estimados en productos, carrito y checkout.</p></article><article className="cdStep"><span className="cdStepNumber">3</span><h3>Disfrutá beneficios</h3><p>Explorá recompensas y probá un canje ficticio en esta demo.</p></article></div></section><section className="cdEditorial"><h2>Más puntos, más recompensas</h2><p>Estas son recompensas de ejemplo. Sus puntos y disponibilidad no representan ofertas activas.</p><div className="cdRewards">{rewards.map(r=><article className="cdCard cdReward" key={"editorial-"+r.id}><div className="cdRewardVisual" aria-hidden="true">{r.id==="cafe"?"☕":r.id==="papas"?"🍟":"🥯"}</div><h3>{r.name}</h3><p className="cdMuted">{r.detail}</p><strong>{r.cost} puntos</strong><button className="cdButton" onClick={()=>{setTab("premios");redeem(r.id)}}>{balance>=r.cost?"Simular canje":"Ver cuánto me falta"}</button></article>)}</div></section><section className="cdFaq"><div className="cdEditorial"><h2>Preguntas frecuentes</h2><p>Lo que necesitás saber sobre esta demostración de CHE Club.</p></div>{faqs.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</section>
 {notice&&<p className="cdNotice" role="status">{notice}</p>}<p className="cdFine"><b>Presentación comercial, no programa activo.</b> Los puntos y canjes se simulan únicamente en este navegador, no se guardan en PostgreSQL, no afectan pedidos reales y se reinician al recargar la página.</p></div></main>
}